server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservicios
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  application:
    name: HOTEL-SERVICE

  cloud:
  config:
    import: optional:configserver:http://localhost:8092




#feign:
#  hystrix:
#    enabled: true
